export default {
    ADD_SITE_TO_SELECTED_WORKSPACE: 'ADD_SITE_TO_SELECTED_WORKSPACE',
    ADD_WORKSPACE: "ADD_WORKSPACE",
    ADD_SITE: "ADD_SITE",
    TOGGLE_FAVORITE: "TOGGLE_FAVORITE",
    REMOVE_SITE: 'REMOVE_SITE',
    REMOVE_SITE_FROM_SELECTED_WORKSPACE: 'REMOVE_SITE_FROM_SELECTED_WORKSPACE',
    REMOVE_WORKSPACE: "REMOVE_WORKSPACE",
    SELECT_WORKSPACE: 'SELECT_WORKSPACE',
    SET_SEARCH_FILTER: 'SET_SEARCH_FILTER',
    TOGGLE_WORKSPACE_MODAL: 'TOGGLE_WORKSPACE_MODAL',
    UNSELECT_WORKSPACE: 'UNSELECT_WORKSPACE',
    UPDATE_WORKSPACE: "UPDATE_WORKSPACE",
}