export default {
    ADD_WORKSPACE: "ADD_WORKSPACE",
    REMOVE_WORKSPACE: "REMOVE_WORKSPACE",
    SELECT_WORKSPACE: 'SELECT_WORKSPACE',
    TOGGLE_WORKSPACE_MODAL: 'TOGGLE_WORKSPACE_MODAL',
    UNSELECT_WORKSPACE: 'UNSELECT_WORKSPACE',
    UPDATE_WORKSPACE: "UPDATE_WORKSPACE",
}